#! /bin/sh


#
# Function that starts the daemon/service
#
do_start()
{
   echo "starting ltsp-ldap (dummy)"

   # todo: tweak configs here

   service libnss-ldap start
   service nslcd start
} 


#
# Function that stops the daemon/service
#
do_stop()
{
   echo "stopping ltsp-ldap (dummy)"
   service libnss-ldap stop
   service nslcd stop
}




  case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
  esac

  exit 

