#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO


#
# Function that starts the daemon/service
#
do_start()
{
   echo "starting ltsp-ldap"

   LDAP_URL=$(getltscfg LDAP_URL)
   LDAP_BASE=$(getltscfg LDAP_BASE)
   if [ -z $LDAP_BASE ] || [ -z $LDAP_URL ]; then
     echo "missing ldap parameter in /etc/lts.conf"
     exit
   fi
   
   sed "s/^base .*$/base ${LDAP_BASE}/" -i /etc/ldap.conf
   sed "s%^uri .*$%uri ${LDAP_URL}%" -i /etc/ldap.conf
 

   service libnss-ldap start
   service nslcd start
} 


#
# Function that stops the daemon/service
#
do_stop()
{
   echo "stopping ltsp-ldap (dummy)"
   LDAP_URL=$(getltscfg LDAP_URL)
   LDAP_BASE=$(getltscfg LDAP_BASE)
   if [ -z $LDAP_BASE ] || [ -z $LDAP_URL ]; then
     echo "missing ldap parameter in /etc/lts.conf"
     exit
   fi
   
   service libnss-ldap stop
   service nslcd stop
}




  case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
  esac

  exit 

